### ISSUE TITLE
Issue when updating to 1.9.3

### ISSUE THREAD

**Issue by manuel-sejourne** [trustedshops/trustedshops-android-sdk#8]
Hi,

I was on the version 1.9.1. et I want to update the SDK to 1.9.3.

I have this issue : 
`Error:(13, 39) error: package org.apache.commons.codec.binary does not exist
Error:(294, 41) error: cannot find symbol variable DigestUtils
Error:(294, 27) error: cannot find symbol variable Hex
Error:(14, 39) error: package org.apache.commons.codec.digest does not exist`

Do you know why ? Do you have a changelog of your SDK releases ?

Thank you.

**Comment by GeroHerkenrath** [comment]
This is weird... It appears as if the SDK can't find Apache's codec classes that are used in `TextUtil.java` (which consists of some helper methods we use to mess with encoding an SKU for product reviews).

In the example project it does find the classes, they're definitely included in the gradle file.
Apache's packages have cause an issue before, see PR #6 (thanks again to @fmarais). It seems the Play Console doesn't work properly when you included them by e.g. 
`implementation 'org.apache.directory.studio:org.apache.commons.codec:1.8'`, so we changed that to 
`implementation group: 'commons-codec', name: 'commons-codec', version: '1.11'`. 

My hunch is that your project includes that already in the first way (which would, btw, ultimately result in your app being reported as compatible with 0 devices on the PlayStore console if it worked, see PR #6). Gradle then ignores the dependency we defined using the `implementation group ...` string as it already considers it to be met and this somehow confuses the compiler (maybe the package was re-organized, i.e. locations of classes changed).

As I said it is only a guess. Could you check your project's gradle file and see if you import apache's classes using `implementation 'org.apache.directory.studio:org.apache.commons ...` somewhere (or `compile ...` if you are still using the "old way"). 

In our case we had to ultimately replace this:
```
    implementation 'org.apache.directory.studio:org.apache.commons.codec:1.8'
    testImplementation 'org.apache.directory.studio:org.apache.commons.io:2.4'
```
with this:
```
    implementation group: 'commons-codec', name: 'commons-codec', version: '1.11'
    testImplementation 'commons-io:commons-io:2.4'
```

Perhaps you can use this as a starting point to debug. You can also post your gradle file and let me have a look at it if you want.

Btw, I am sorry we don't have a properly maintained changelog. Obviously we do have an internal one, but that is a mess due to some legacy stuff and wouldn't help you much. We will remedy that at some point in the future.

**Comment by manuel-sejourne** [comment]
Hi ! 

Thanks for your answer. I have not the commons-codec in my app, maybe it is the problem.

I think you changed the visibility of your dependencies, it is why I have this issue.

When I launch "./gradlew mobile:dependencies" I see nothing under your SDK-lib on this version but all the libs included in the older version (1.9.1). So it confirms that I have to add this line (for a personal usage in my app) : 
implementation group: 'commons-codec', name: 'commons-codec', version: '1.11'

But I have another issue when compiling : 

> Warning:com.trustedshops.androidsdk.trustbadge.JsInterface:
 can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:com.trustedshops.androidsdk.trustbadge.Trustbadge$2: can't find referenced class com.afollestad.materialdialogs.MaterialDialog$Builder
Warning:com.trustedshops.androidsdk.trustbadge.Trustbadge$2: can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:com.trustedshops.androidsdk.trustbadge.Trustbadge$2: can't find referenced class com.afollestad.materialdialogs.MaterialDialog$Builder
Warning:com.trustedshops.androidsdk.trustbadge.Trustbadge$2: can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:com.trustedshops.androidsdk.trustbadge.Trustbadge$2$3: can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:com.trustedshops.androidsdk.trustbadge.Trustbadge$2$3$1: can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:com.trustedshops.androidsdk.trustbadge.TrustedShopsCheckout: can't find referenced class com.afollestad.materialdialogs.MaterialDialog$Builder
Warning:com.trustedshops.androidsdk.trustbadge.TrustedShopsCheckout: can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:com.trustedshops.androidsdk.trustbadge.TrustedShopsCheckout: can't find referenced class com.afollestad.materialdialogs.MaterialDialog$Builder
Warning:com.trustedshops.androidsdk.trustbadge.TrustedShopsCheckout: can't find referenced class com.afollestad.materialdialogs.MaterialDialog
Warning:there were 31 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task :mobile:transformClassesAndResourcesWithProguardForDevelopDebug.
> Job failed, see logs for details

Any idea ?

**Comment by GeroHerkenrath** [comment]
Oh boy, that was a tough one, but it should be fixed now with PR #9 and version v1.9.4.

It turns out that the maven/bintray plugin, for whatever reason, didn't include the dependencies in the POM file anymore. I assume it had to do with the change from using the "compile" command to "implementation". I fixed it by manually adding the necessary nodes in gradle.

The reason we didn't see it before was that it is only visible when you actually include the library via gradle, i.e. load it from bintray. The example project obviously just uses the SDK subdirectory directly, and there the needed dependencies are found. I'm sorry for the confusion.

I now tested it with a fresh test project that includes the library exactly like you would in a production project. Let me know if there's anything else wrong.

(Sidenote: I didn't have the time to update the material dialog dependency, which now introduces an older appcompat version to your project, `com.android.support:appcompat-v7:27.0.1` instead of `com.android.support:appcompat-v7:27.1.1`. This should not lead to any issues, however)
